Fix zpool spec failure on ruby 1.9
At least when running ruby 1.9 I observed the following spec errors

    Failure/Error: @provider.create
    NoMethodError:
    undefined method `collect' for "shouldvalue":String

This can happen because the disk property both allow an array or a space
separated string. If we just have a simple string we have to make sure
to convert it into an array before running collect.